#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHARD_INDEX="${1:?missing shard index}"
SHARD_COUNT="${2:?missing shard count}"

if [[ -f "${ROOT_DIR}/config/runtime.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/config/runtime.env"
  set +a
fi

export PORT="$((3600 + SHARD_INDEX))"
export HOST="127.0.0.1"
export PACIFICA_SERVICE="api"
export PACIFICA_WS_ENABLED="false"
export PACIFICA_SNAPSHOT_ENABLED="false"
export PACIFICA_GLOBAL_KPI_ENABLED="false"
export PACIFICA_INDEXER_ENABLED="false"
export PACIFICA_INDEXER_RUNNER_ENABLED="false"
export PACIFICA_ONCHAIN_ENABLED="false"
export PACIFICA_ONCHAIN_RUNNER_ENABLED="false"
export PACIFICA_PIPELINE_SKIP_REPLAY="true"
export PACIFICA_LIVE_WALLET_FIRST_ENABLED="true"
export PACIFICA_LIVE_WALLET_FIRST_SHARD_COUNT="${SHARD_COUNT}"
export PACIFICA_LIVE_WALLET_FIRST_SHARD_INDEX="${SHARD_INDEX}"
export PACIFICA_LIVE_WALLET_FIRST_TARGET_PASS_MS="12000"
export PACIFICA_LIVE_WALLET_FIRST_REQUEST_TIMEOUT_MS="3000"
export PACIFICA_LIVE_WALLET_FIRST_MAX_FETCH_ATTEMPTS="2"
export PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY="32"
export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT="4"
export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT="1"
export PACIFICA_LIVE_WALLET_FIRST_HOT_WALLETS_PER_PASS="64"
export PACIFICA_LIVE_WALLET_FIRST_WARM_WALLETS_PER_PASS="128"
export PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVE_WALLETS_PER_PASS="64"
export PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVITY_TTL_MS="1800000"
export PACIFICA_LIVE_WALLET_FIRST_WARM_WALLET_RECENT_MS="259200000"
export PACIFICA_LIVE_WALLET_FIRST_MAX_WARM_WALLETS="4000"
export PACIFICA_LIVE_TRADE_ATTRIBUTION_DB_ENABLED="false"
export PACIFICA_LIVE_TRADE_WALLET_ATTRIBUTION_ENABLED="false"
export PACIFICA_LIVE_TRADE_TX_ATTRIBUTION_ENABLED="false"
export PACIFICA_MULTI_EGRESS_INCLUDE_DIRECT="false"
export PACIFICA_MULTI_EGRESS_PROXY_FILE="${ROOT_DIR}/data/live_positions/proxy_shards/proxies_${SHARD_INDEX}.txt"
export PACIFICA_LIVE_WALLET_FIRST_INCLUDE_DIRECT="false"

exec /usr/bin/node "${ROOT_DIR}/server.js"
