#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INSTANCE_INDEX="${1:-0}"
INSTANCE_COUNT="${2:-4}"
LANE_MODE="${3:-auto}"

if [[ -f "${ROOT_DIR}/config/runtime.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/config/runtime.env"
  set +a
fi

if [[ "${LANE_MODE}" == "auto" ]]; then
  HISTORY_WORKERS="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_WORKERS:-1}"
  HISTORY_HEAVY_WORKERS="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_WORKERS:-0}"
  LIVE_WORKERS="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_WORKERS:-1}"
  GAP_WORKERS="$(( INSTANCE_COUNT - HISTORY_WORKERS - HISTORY_HEAVY_WORKERS - LIVE_WORKERS ))"
  if (( GAP_WORKERS < 1 )); then
    GAP_WORKERS=1
    HISTORY_WORKERS=$(( INSTANCE_COUNT - HISTORY_HEAVY_WORKERS - LIVE_WORKERS - GAP_WORKERS ))
    if (( HISTORY_WORKERS < 1 )); then
      HISTORY_WORKERS=1
      HISTORY_HEAVY_WORKERS=$(( INSTANCE_COUNT - HISTORY_WORKERS - LIVE_WORKERS - GAP_WORKERS ))
      if (( HISTORY_HEAVY_WORKERS < 0 )); then
        HISTORY_HEAVY_WORKERS=0
      fi
      LIVE_WORKERS=$(( INSTANCE_COUNT - HISTORY_WORKERS - HISTORY_HEAVY_WORKERS - GAP_WORKERS ))
      if (( LIVE_WORKERS < 1 )); then
        LIVE_WORKERS=1
      fi
    fi
  fi
  if (( INSTANCE_COUNT >= 5 )); then
    if (( INSTANCE_INDEX < HISTORY_WORKERS )); then
      LANE_MODE="history"
    elif (( INSTANCE_INDEX < HISTORY_WORKERS + HISTORY_HEAVY_WORKERS )); then
      LANE_MODE="history_heavy"
    elif (( INSTANCE_INDEX >= INSTANCE_COUNT - LIVE_WORKERS )); then
      LANE_MODE="live"
    else
      LANE_MODE="gap"
    fi
  else
    case "${INSTANCE_INDEX}" in
      0) LANE_MODE="history" ;;
      1) LANE_MODE="gap" ;;
      2) LANE_MODE="gap" ;;
      *) LANE_MODE="live" ;;
    esac
  fi
fi

REVIEW_DIR="${ROOT_DIR}/data/wallet_explorer_v2/review_pipeline"
mkdir -p "${REVIEW_DIR}"

MASTER_PROXY_FILE="${PACIFICA_MULTI_EGRESS_PROXY_FILE:-${ROOT_DIR}/data/indexer/working_proxies.txt}"
PROXY_SHARD_DIR="${REVIEW_DIR}/proxy_shards_${LANE_MODE}_${INSTANCE_INDEX}"
mkdir -p "${PROXY_SHARD_DIR}"
find "${PROXY_SHARD_DIR}" -maxdepth 1 -type f -name '*.txt' -delete

TOTAL_PARALLELISM="${PACIFICA_WALLET_REVIEW_RUNTIME_TOTAL_PARALLELISM:-32}"
TOTAL_RESERVED_PROXIES="${PACIFICA_WALLET_REVIEW_RUNTIME_TOTAL_RESERVED_PROXIES:-1000}"
HISTORY_LIMIT="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_LIMIT:-60}"
GAP_LIMIT="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_LIMIT:-25}"
PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_PAGE_BUDGET:-2}"
DEEP_REPAIR_PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_DEEP_REPAIR_PAGE_BUDGET:-4}"
GAP_PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_PAGE_BUDGET:-4}"
EXTRA_HISTORY_CHECKS="${PACIFICA_WALLET_REVIEW_RUNTIME_EXTRA_HISTORY_CHECKS:-2}"
TRANSITION_POLL_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_TRANSITION_POLL_MS:-300000}"
MIN_TRANSITION_WINDOW_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_MIN_TRANSITION_WINDOW_MS:-120000}"
MAX_TRANSITION_WINDOW_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_MAX_TRANSITION_WINDOW_MS:-900000}"
LIVE_POLL_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_POLL_MS:-3600000}"
TIMEOUT_SECONDS="${PACIFICA_WALLET_REVIEW_RUNTIME_TIMEOUT_SECONDS:-20}"
GAP_RETRY_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_RETRY_MS:-300000}"
LOOP_SLEEP_SECONDS="${PACIFICA_WALLET_REVIEW_RUNTIME_LOOP_SLEEP_SECONDS:-0.1}"
CLAIM_BATCH_SIZE="${PACIFICA_WALLET_REVIEW_RUNTIME_CLAIM_BATCH_SIZE:-4}"

DEFAULT_PARALLELISM="$(( (TOTAL_PARALLELISM + INSTANCE_COUNT - 1) / INSTANCE_COUNT ))"
DEFAULT_RESERVED_PROXY_COUNT="$(( (TOTAL_RESERVED_PROXIES + INSTANCE_COUNT - 1) / INSTANCE_COUNT ))"

PARALLELISM="${DEFAULT_PARALLELISM}"
RESERVED_PROXY_COUNT="${DEFAULT_RESERVED_PROXY_COUNT}"

case "${LANE_MODE}" in
  history)
    PARALLELISM="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_PARALLELISM:-${PARALLELISM}}"
    RESERVED_PROXY_COUNT="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_RESERVED_PROXIES:-${RESERVED_PROXY_COUNT}}"
    HISTORY_LIMIT="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HISTORY_LIMIT:-${HISTORY_LIMIT}}"
    PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_PAGE_BUDGET:-${PAGE_BUDGET}}"
    DEEP_REPAIR_PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_DEEP_REPAIR_PAGE_BUDGET:-${DEEP_REPAIR_PAGE_BUDGET}}"
    EXTRA_HISTORY_CHECKS="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_EXTRA_CHECKS:-${EXTRA_HISTORY_CHECKS}}"
    ;;
  history_heavy)
    PARALLELISM="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_PARALLELISM:-${PARALLELISM}}"
    RESERVED_PROXY_COUNT="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_RESERVED_PROXIES:-${RESERVED_PROXY_COUNT}}"
    HISTORY_LIMIT="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_HISTORY_LIMIT:-${HISTORY_LIMIT}}"
    PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_PAGE_BUDGET:-${PAGE_BUDGET}}"
    DEEP_REPAIR_PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_DEEP_REPAIR_PAGE_BUDGET:-${DEEP_REPAIR_PAGE_BUDGET}}"
    EXTRA_HISTORY_CHECKS="${PACIFICA_WALLET_REVIEW_RUNTIME_HISTORY_HEAVY_EXTRA_CHECKS:-${EXTRA_HISTORY_CHECKS}}"
    ;;
  gap)
    PARALLELISM="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_PARALLELISM:-${PARALLELISM}}"
    RESERVED_PROXY_COUNT="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_RESERVED_PROXIES:-${RESERVED_PROXY_COUNT}}"
    GAP_LIMIT="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_GAP_LIMIT:-${GAP_LIMIT}}"
    GAP_PAGE_BUDGET="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_PAGE_BUDGET_MODE:-${GAP_PAGE_BUDGET}}"
    GAP_RETRY_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_GAP_RETRY_MS_MODE:-${GAP_RETRY_MS}}"
    ;;
  live)
    PARALLELISM="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_PARALLELISM:-${PARALLELISM}}"
    RESERVED_PROXY_COUNT="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_RESERVED_PROXIES:-${RESERVED_PROXY_COUNT}}"
    TRANSITION_POLL_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_TRANSITION_POLL_MS:-${TRANSITION_POLL_MS}}"
    LIVE_POLL_MS="${PACIFICA_WALLET_REVIEW_RUNTIME_LIVE_POLL_MS_MODE:-${LIVE_POLL_MS}}"
    ;;
esac

PARALLELISM="$(( PARALLELISM > 0 ? PARALLELISM : 1 ))"
RESERVED_PROXY_COUNT="$(( RESERVED_PROXY_COUNT > 0 ? RESERVED_PROXY_COUNT : 1 ))"

python3 - <<'PY' "${MASTER_PROXY_FILE}" "${PROXY_SHARD_DIR}" "${RESERVED_PROXY_COUNT}" "${PARALLELISM}" "${INSTANCE_INDEX}" "${INSTANCE_COUNT}"
import pathlib, sys

src = pathlib.Path(sys.argv[1])
out_dir = pathlib.Path(sys.argv[2])
reserved = max(1, int(sys.argv[3]))
parallelism = max(1, int(sys.argv[4]))
instance_index = int(sys.argv[5])
instance_count = max(1, int(sys.argv[6]))
rows = []
if src.exists():
    rows = [
        line.strip()
        for line in src.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
subset = rows[-(reserved * instance_count):] if len(rows) > (reserved * instance_count) else rows
if instance_count > 1:
    subset = [row for idx, row in enumerate(subset) if idx % instance_count == instance_index]
subset = subset[-reserved:] if len(subset) > reserved else subset
for lane in range(parallelism):
    dst = out_dir / f"proxies_{lane}.txt"
    dst.write_text("")
if not subset:
    raise SystemExit(0)
per = max(1, (len(subset) + parallelism - 1) // parallelism)
for lane in range(parallelism):
    start = lane * per
    end = min(len(subset), start + per)
    lane_rows = subset[start:end]
    dst = out_dir / f"proxies_{lane}.txt"
    dst.write_text("\n".join(lane_rows) + ("\n" if lane_rows else ""))
PY

exec python3 \
  "${ROOT_DIR}/scripts/wallet_explorer_v2/review_async_runtime.py" \
  --db-path "${REVIEW_DIR}/runtime.sqlite3" \
  --proxy-dir "${PROXY_SHARD_DIR}" \
  --shard-count "${PACIFICA_WALLET_EXPLORER_V2_SHARDS:-8}" \
  --timeout-seconds "${TIMEOUT_SECONDS}" \
  --parallelism "${PARALLELISM}" \
  --lane-mode "${LANE_MODE}" \
  --history-limit "${HISTORY_LIMIT}" \
  --gap-limit "${GAP_LIMIT}" \
  --page-budget "${PAGE_BUDGET}" \
  --deep-repair-page-budget "${DEEP_REPAIR_PAGE_BUDGET}" \
  --gap-page-budget "${GAP_PAGE_BUDGET}" \
  --extra-history-checks "${EXTRA_HISTORY_CHECKS}" \
  --gap-retry-ms "${GAP_RETRY_MS}" \
  --loop-sleep-seconds "${LOOP_SLEEP_SECONDS}" \
  --claim-batch-size "${CLAIM_BATCH_SIZE}" \
  --transition-poll-ms "${TRANSITION_POLL_MS}" \
  --min-transition-window-ms "${MIN_TRANSITION_WINDOW_MS}" \
  --max-transition-window-ms "${MAX_TRANSITION_WINDOW_MS}" \
  --live-poll-ms "${LIVE_POLL_MS}"
