#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHARD_INDEX="${1:?missing shard index}"
SHARD_COUNT="${2:?missing shard count}"
WORKER_MODE="${3:-combined}"
LIVE_PROXY_BUDGET_DEFAULT="500"

if [[ -f "${ROOT_DIR}/config/runtime.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/config/runtime.env"
  set +a
fi

LIVE_PROXY_BUDGET="${PACIFICA_LIVE_POSITIONS_PROXY_BUDGET:-$LIVE_PROXY_BUDGET_DEFAULT}"
LIVE_PROXY_SOURCE_FILE="${ROOT_DIR}/data/live_positions/positions_proxies.txt"
LIVE_PROXY_SHARD_DIR="${ROOT_DIR}/data/live_positions/proxy_shards"

if [[ "${WORKER_MODE}" == "account_census" ]]; then
  LIVE_PROXY_BUDGET="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_PROXY_BUDGET:-${LIVE_PROXY_BUDGET}}"
  if [[ -n "${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_PROXY_FILE:-}" ]]; then
    LIVE_PROXY_SOURCE_FILE="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_PROXY_FILE}"
  elif [[ -f "${ROOT_DIR}/data/live_positions/detector_proxies.txt" ]]; then
    LIVE_PROXY_SOURCE_FILE="${ROOT_DIR}/data/live_positions/detector_proxies.txt"
  fi
  LIVE_PROXY_SHARD_DIR="${ROOT_DIR}/data/live_positions/detector_proxy_shards"
fi

LIVE_PROXY_LOCK_FILE="${LIVE_PROXY_SHARD_DIR}/.split.lock"

mkdir -p "${LIVE_PROXY_SHARD_DIR}"
exec 9>"${LIVE_PROXY_LOCK_FILE}"
flock 9
"${ROOT_DIR}/scripts/split_live_positions_proxies.sh" \
  "${SHARD_COUNT}" \
  "${LIVE_PROXY_BUDGET}" \
  "${LIVE_PROXY_SOURCE_FILE}" \
  "${LIVE_PROXY_SHARD_DIR}" >/dev/null
flock -u 9

export PORT="$((3600 + SHARD_INDEX))"
export HOST="127.0.0.1"
export PACIFICA_SERVICE="api"
export PACIFICA_WS_ENABLED="false"
export PACIFICA_SNAPSHOT_ENABLED="false"
export PACIFICA_GLOBAL_KPI_ENABLED="false"
export PACIFICA_INDEXER_ENABLED="false"
export PACIFICA_INDEXER_EXTERNAL_SHARDS_ENABLED="false"
export PACIFICA_INDEXER_MULTI_WORKER_SHARDS="1"
export PACIFICA_INDEXER_RUNNER_ENABLED="false"
export PACIFICA_ONCHAIN_ENABLED="false"
export PACIFICA_ONCHAIN_RUNNER_ENABLED="false"
export PACIFICA_SOLANA_LOG_TRIGGER_ENABLED="false"
export PACIFICA_PIPELINE_SKIP_REPLAY="true"
export PACIFICA_LIVE_WALLET_FIRST_ENABLED="true"
export PACIFICA_LIVE_WALLET_FIRST_EXTERNAL_SHARDS="false"
export PACIFICA_LIVE_WALLET_FIRST_WORKER_MODE="${WORKER_MODE}"
export PACIFICA_LIVE_WALLET_FIRST_SHARD_COUNT="${SHARD_COUNT}"
export PACIFICA_LIVE_WALLET_FIRST_SHARD_INDEX="${SHARD_INDEX}"
export PACIFICA_LIVE_WALLET_FIRST_WALLET_DATASET_PATH="${PACIFICA_LIVE_WALLET_FIRST_WALLET_DATASET_PATH:-${ROOT_DIR}/data/live_positions/positive_wallet_rows_snapshot.json}"
export PACIFICA_LIVE_WALLET_FIRST_WALLET_DATASET_REFRESH_MS="${PACIFICA_LIVE_WALLET_FIRST_WALLET_DATASET_REFRESH_MS:-30000}"
export PACIFICA_LIVE_WALLET_FIRST_SCAN_INTERVAL_MS="${PACIFICA_LIVE_WALLET_FIRST_SCAN_INTERVAL_MS:-500}"
export PACIFICA_LIVE_WALLET_FIRST_TARGET_PASS_MS="${PACIFICA_LIVE_WALLET_FIRST_TARGET_PASS_MS:-4000}"
export PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS:-1024}"
export PACIFICA_LIVE_WALLET_FIRST_REQUEST_TIMEOUT_MS="${PACIFICA_LIVE_WALLET_FIRST_REQUEST_TIMEOUT_MS:-3500}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_REQUEST_TIMEOUT_MS="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_REQUEST_TIMEOUT_MS:-9000}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_REQUEST_TIMEOUT_MS="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_REQUEST_TIMEOUT_MS:-10000}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_FETCH_ATTEMPTS="${PACIFICA_LIVE_WALLET_FIRST_MAX_FETCH_ATTEMPTS:-2}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_FETCH_ATTEMPTS="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_FETCH_ATTEMPTS:-3}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_FETCH_ATTEMPTS="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_FETCH_ATTEMPTS:-2}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY:-96}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_CONCURRENCY:-32}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT="${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT:-3}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT:-3}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_PER_CLIENT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_PER_CLIENT:-1}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_DIRECT:-1}"
export PACIFICA_LIVE_WALLET_FIRST_DIRECT_FALLBACK_ON_LAST_ATTEMPT="${PACIFICA_LIVE_WALLET_FIRST_DIRECT_FALLBACK_ON_LAST_ATTEMPT:-false}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_DIRECT_FALLBACK_ON_LAST_ATTEMPT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_DIRECT_FALLBACK_ON_LAST_ATTEMPT:-true}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_DIRECT_FALLBACK_ON_LAST_ATTEMPT="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_DIRECT_FALLBACK_ON_LAST_ATTEMPT:-true}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_REQUEST_TIMEOUT_MS="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_REQUEST_TIMEOUT_MS:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_REQUEST_TIMEOUT_MS}}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_FETCH_ATTEMPTS="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_FETCH_ATTEMPTS:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_FETCH_ATTEMPTS}}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_DIRECT_FALLBACK_ON_LAST_ATTEMPT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_DIRECT_FALLBACK_ON_LAST_ATTEMPT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_DIRECT_FALLBACK_ON_LAST_ATTEMPT}}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_INCLUDE_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_INCLUDE_DIRECT:-true}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_INCLUDE_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_INCLUDE_DIRECT:-false}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_INCLUDE_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_INCLUDE_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_INCLUDE_DIRECT}}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_PROXY_COUNT_PER_SHARD="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_PROXY_COUNT_PER_SHARD:-80}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_PROXY_COUNT_PER_SHARD="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_PROXY_COUNT_PER_SHARD:-80}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_PROXY_COUNT_PER_SHARD="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_PROXY_COUNT_PER_SHARD:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_PROXY_COUNT_PER_SHARD}}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_PER_CLIENT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_PER_CLIENT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_INFLIGHT_PER_CLIENT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT}}}"
export PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_INFLIGHT_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT}}}"
export PACIFICA_LIVE_WALLET_FIRST_BOOTSTRAP_WALLET_SEED_LIMIT="${PACIFICA_LIVE_WALLET_FIRST_BOOTSTRAP_WALLET_SEED_LIMIT:-10000}"
export PACIFICA_LIVE_WALLET_FIRST_RATE_LIMIT_BACKOFF_BASE_MS="${PACIFICA_LIVE_WALLET_FIRST_RATE_LIMIT_BACKOFF_BASE_MS:-750}"
export PACIFICA_LIVE_WALLET_FIRST_RATE_LIMIT_BACKOFF_MAX_MS="${PACIFICA_LIVE_WALLET_FIRST_RATE_LIMIT_BACKOFF_MAX_MS:-8000}"
export PACIFICA_LIVE_WALLET_FIRST_HOT_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_HOT_WALLETS_PER_PASS:-224}"
export PACIFICA_LIVE_WALLET_FIRST_WARM_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_WARM_WALLETS_PER_PASS:-160}"
export PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVE_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVE_WALLETS_PER_PASS:-160}"
export PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVITY_TTL_MS="${PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVITY_TTL_MS:-1800000}"
export PACIFICA_LIVE_WALLET_FIRST_WARM_WALLET_RECENT_MS="${PACIFICA_LIVE_WALLET_FIRST_WARM_WALLET_RECENT_MS:-259200000}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_WARM_WALLETS="${PACIFICA_LIVE_WALLET_FIRST_MAX_WARM_WALLETS:-10000}"
export PACIFICA_LIVE_WALLET_FIRST_HOT_RECONCILE_MAX_AGE_MS="${PACIFICA_LIVE_WALLET_FIRST_HOT_RECONCILE_MAX_AGE_MS:-10000}"
export PACIFICA_LIVE_WALLET_FIRST_WARM_RECONCILE_MAX_AGE_MS="${PACIFICA_LIVE_WALLET_FIRST_WARM_RECONCILE_MAX_AGE_MS:-120000}"
export PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_COOLDOWN_MS="${PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_COOLDOWN_MS:-120}"
export PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_MAX_CONCURRENCY:-48}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_COOLDOWN_MS="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_COOLDOWN_MS:-120}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_MAX_CONCURRENCY:-96}"
export PACIFICA_LIVE_WALLET_FIRST_WS_ACCOUNT_INFO_TRIGGER_DEDUP_MS="${PACIFICA_LIVE_WALLET_FIRST_WS_ACCOUNT_INFO_TRIGGER_DEDUP_MS:-1000}"
export PACIFICA_LIVE_WALLET_FIRST_HOT_OPEN_TRIGGER_DEDUP_MS="${PACIFICA_LIVE_WALLET_FIRST_HOT_OPEN_TRIGGER_DEDUP_MS:-1200}"
export PACIFICA_LIVE_WALLET_TRIGGER_POLL_MS="${PACIFICA_LIVE_WALLET_TRIGGER_POLL_MS:-250}"
export PACIFICA_HOT_WALLET_WS_MAX_WALLETS="${PACIFICA_HOT_WALLET_WS_MAX_WALLETS:-4096}"
export PACIFICA_HOT_WALLET_WS_INITIAL_WALLETS="${PACIFICA_HOT_WALLET_WS_INITIAL_WALLETS:-2048}"
export PACIFICA_HOT_WALLET_WS_CAPACITY_STEP="${PACIFICA_HOT_WALLET_WS_CAPACITY_STEP:-512}"
export PACIFICA_HOT_WALLET_WS_SOAK_WINDOW_MS="${PACIFICA_HOT_WALLET_WS_SOAK_WINDOW_MS:-5000}"
export PACIFICA_HOT_WALLET_WS_MAX_SCALE_ERRORS="${PACIFICA_HOT_WALLET_WS_MAX_SCALE_ERRORS:-64}"
export PACIFICA_HOT_WALLET_WS_MAX_SCALE_RECONNECTS="${PACIFICA_HOT_WALLET_WS_MAX_SCALE_RECONNECTS:-512}"
export PACIFICA_HOT_WALLET_WS_MIN_SCALE_UTILIZATION_PCT="${PACIFICA_HOT_WALLET_WS_MIN_SCALE_UTILIZATION_PCT:-50}"
export PACIFICA_HOT_WALLET_WS_MIN_SCALE_BACKLOG="${PACIFICA_HOT_WALLET_WS_MIN_SCALE_BACKLOG:-1}"
export PACIFICA_HOT_WALLET_WS_MEMORY_CEILING_MB="${PACIFICA_HOT_WALLET_WS_MEMORY_CEILING_MB:-2048}"
export PACIFICA_HOT_WALLET_WS_INACTIVITY_MS="${PACIFICA_HOT_WALLET_WS_INACTIVITY_MS:-45000}"
export PACIFICA_HOT_WALLET_WS_TRADE_HOLD_MS="${PACIFICA_HOT_WALLET_WS_TRADE_HOLD_MS:-60000}"
export PACIFICA_HOT_WALLET_WS_OPEN_POSITION_HOLD_MS="${PACIFICA_HOT_WALLET_WS_OPEN_POSITION_HOLD_MS:-300000}"
export PACIFICA_HOT_WALLET_WS_AGGRESSIVE_EVICT_MS="${PACIFICA_HOT_WALLET_WS_AGGRESSIVE_EVICT_MS:-5000}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ACCOUNT_INFO="${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ACCOUNT_INFO_OVERRIDE:-${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ACCOUNT_INFO:-false}}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_POSITIONS="${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_POSITIONS_OVERRIDE:-${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_POSITIONS:-true}}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_TRADES="${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_TRADES_OVERRIDE:-${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_TRADES:-true}}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ORDER_UPDATES="${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ORDER_UPDATES_OVERRIDE:-${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ORDER_UPDATES:-true}}"
export PACIFICA_LIVE_WALLET_FIRST_PERSIST_EVERY_MS="${PACIFICA_LIVE_WALLET_FIRST_PERSIST_EVERY_MS:-1000}"

if [[ "${WORKER_MODE}" == "account_census" ]]; then
  export PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_WALLETS_PER_PASS:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_WALLETS_PER_PASS:-${PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS}}}"
  export PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_CONCURRENCY:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_CONCURRENCY:-${PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY}}}"
  export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_PER_CLIENT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_INFLIGHT_PER_CLIENT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT}}}"
  export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_DETECTOR_MAX_INFLIGHT_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_INFLIGHT_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT}}}"
elif [[ "${WORKER_MODE}" == "positions_materializer" ]]; then
  export PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_CONCURRENCY:-${PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY}}"
  export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_PER_CLIENT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_PER_CLIENT}}"
  export PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_INFLIGHT_DIRECT:-${PACIFICA_LIVE_WALLET_FIRST_MAX_INFLIGHT_DIRECT}}"
  export PACIFICA_LIVE_WALLET_FIRST_WS_HOT_ONLY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_HOT_ONLY:-${PACIFICA_LIVE_WALLET_FIRST_WS_HOT_ONLY:-true}}"
  export PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_COOLDOWN_MS="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_COOLDOWN_MS:-${PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_COOLDOWN_MS}}"
  export PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_WS_RECONCILE_MAX_CONCURRENCY:-${PACIFICA_LIVE_WALLET_FIRST_WS_RECONCILE_MAX_CONCURRENCY}}"
fi

export PACIFICA_SOLANA_LOG_TRIGGER_MAX_WALLET_CANDIDATES="${PACIFICA_SOLANA_LOG_TRIGGER_MAX_WALLET_CANDIDATES:-6}"
export PACIFICA_LIVE_TRADE_ATTRIBUTION_DB_ENABLED="false"
export PACIFICA_LIVE_TRADE_WALLET_ATTRIBUTION_ENABLED="false"
export PACIFICA_LIVE_TRADE_TX_ATTRIBUTION_ENABLED="false"
export PACIFICA_MULTI_EGRESS_INCLUDE_DIRECT="${PACIFICA_MULTI_EGRESS_INCLUDE_DIRECT:-false}"
export PACIFICA_MULTI_EGRESS_PROXY_FILE="${LIVE_PROXY_SHARD_DIR}/proxies_${SHARD_INDEX}.txt"
export PACIFICA_LIVE_WALLET_FIRST_INCLUDE_DIRECT="${PACIFICA_LIVE_WALLET_FIRST_INCLUDE_DIRECT:-false}"

NODE_BIN="${NODE_BIN:-$(command -v node || command -v nodejs || true)}"
if [[ -z "${NODE_BIN}" ]]; then
  echo "node binary not found" >&2
  exit 127
fi

exec "${NODE_BIN}" "${ROOT_DIR}/scripts/live_trade_positions_worker.js"
