#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHARD_INDEX="${1:?missing shard index}"
SHARD_COUNT="${2:?missing shard count}"

if [[ -f "${ROOT_DIR}/config/runtime.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/config/runtime.env"
  set +a
fi

export PACIFICA_LIVE_TRADE_BASE_DIR="${PACIFICA_LIVE_TRADE_BASE_DIR:-${ROOT_DIR}/data/live_trade_leaderboard}"
export PACIFICA_LIVE_WALLET_FIRST_WALLET_DATASET_PATH="${PACIFICA_LIVE_TRADE_BASE_DIR}/wallet_dataset.json"
export PACIFICA_LIVE_WALLET_FIRST_PERSIST_DIR="${PACIFICA_LIVE_TRADE_BASE_DIR}/live_positions"
export PACIFICA_LIVE_WALLET_FIRST_PUBLIC_ACTIVE_LEADERBOARD_ENABLED="false"
export PACIFICA_LIVE_WALLET_FIRST_SCAN_INTERVAL_MS="${PACIFICA_LIVE_WALLET_FIRST_SCAN_INTERVAL_MS:-500}"
export PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_WALLETS_PER_PASS:-96}"
export PACIFICA_LIVE_WALLET_FIRST_HOT_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_HOT_WALLETS_PER_PASS:-96}"
export PACIFICA_LIVE_WALLET_FIRST_WARM_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_WARM_WALLETS_PER_PASS:-48}"
export PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVE_WALLETS_PER_PASS="${PACIFICA_LIVE_WALLET_FIRST_RECENT_ACTIVE_WALLETS_PER_PASS:-48}"
export PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_MAX_CONCURRENCY:-64}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_MAX_CONCURRENCY:-48}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_CONCURRENCY="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_MAX_CONCURRENCY:-1}"
export PACIFICA_LIVE_WALLET_FIRST_POSITIONS_PROXY_COUNT_PER_SHARD="${PACIFICA_LIVE_WALLET_FIRST_POSITIONS_PROXY_COUNT_PER_SHARD:-0}"
export PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_PROXY_COUNT_PER_SHARD="${PACIFICA_LIVE_WALLET_FIRST_ACCOUNT_PROXY_COUNT_PER_SHARD:-0}"
export PACIFICA_HOT_WALLET_WS_ENABLED="${PACIFICA_HOT_WALLET_WS_ENABLED:-true}"
export PACIFICA_HOT_WALLET_WS_USE_PROXIES="${PACIFICA_HOT_WALLET_WS_USE_PROXIES:-false}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ALL_DATASET="${PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ALL_DATASET:-false}"
export PACIFICA_HOT_WALLET_WS_MAX_WALLETS="${PACIFICA_HOT_WALLET_WS_MAX_WALLETS:-2048}"
export PACIFICA_HOT_WALLET_WS_INITIAL_WALLETS="${PACIFICA_HOT_WALLET_WS_INITIAL_WALLETS:-1024}"
export PACIFICA_HOT_WALLET_WS_CAPACITY_STEP="${PACIFICA_HOT_WALLET_WS_CAPACITY_STEP:-128}"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ACCOUNT_INFO_OVERRIDE="true"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_POSITIONS_OVERRIDE="false"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_TRADES_OVERRIDE="true"
export PACIFICA_HOT_WALLET_WS_SUBSCRIBE_ORDER_UPDATES_OVERRIDE="true"
export PACIFICA_LIVE_WALLET_FIRST_WS_HOT_ONLY="${PACIFICA_LIVE_WALLET_FIRST_WS_HOT_ONLY:-true}"
export PACIFICA_LIVE_WALLET_FIRST_IGNORE_PERSISTED_EVENTS="${PACIFICA_LIVE_WALLET_FIRST_IGNORE_PERSISTED_EVENTS:-true}"
export PACIFICA_LIVE_WALLET_FIRST_OPEN_EVENT_MAX_LAG_MS="${PACIFICA_LIVE_WALLET_FIRST_OPEN_EVENT_MAX_LAG_MS:-5000}"
export PACIFICA_LIVE_WALLET_FIRST_WS_ACCOUNT_INFO_TRIGGER_DEDUP_MS="${PACIFICA_LIVE_WALLET_FIRST_WS_ACCOUNT_INFO_TRIGGER_DEDUP_MS:-3000}"
export PACIFICA_LIVE_WALLET_FIRST_GAP_RESCUE_SHARE="${PACIFICA_LIVE_WALLET_FIRST_GAP_RESCUE_SHARE:-0.10}"

exec "${ROOT_DIR}/scripts/systemd/run_live_positions_shard.sh" "${SHARD_INDEX}" "${SHARD_COUNT}" "positions_materializer"
